### ISSUE TITLE
Ввод через зад

### ISSUE THREAD

**Issue by artemius1248** [vladon/testtask-eidos#1]
Ну что ж ты делаешь, мил человек. Ну кто ж так с консоли считывает. Адъ ж кромешный. Зачем тебе виртуальный коды клавиш, да еще и в двух вложенных циклах, даже думать боюсь зачем ето все. Сунь обычный гетчар на свитч иили на иф, не огорчай Леонид Аркадьевича. 
Ну а так в целом ниче там, спасибо, заценил.

P.S. Вы нам не подходите, извините.
ООО Эйдос Медицина, ведущий разработчик проекта лапаро

**Comment by vladon** [comment]
@artemius1248 

1) getchar() требует нажатия Enter, в задаче сказано "по нажатию клавиши", а не "по вводу символа и нажатию Enter";
2) getchar() не ловит нажатия + и - на цифровой клавиатуре при выключенном Num Lock;
3) getchar() возвращает не нажатую кнопку клавиатуры, а символ, т.е. даже зависит от текущего языка клавиатуры (EN/RU).

Именно поэтому и был выбран такой способ опроса клавиатуры.

Остальное неконструктивно. Но я рад, что вы ради меня зарегистрировались на гитхабе.

Комментарии будут?

> P.S. Вы нам не подходите, извините.

Слава Богу, что не пришлось работать под началом такого вот специалиста как Вы.

**Comment by artemius1248** [comment]
Если нужно без Ентера - можно _гетч, все равно как то оно поизящнее будет, имхо. Ну что до других доводов могусказать, что если заказчик оставил это в тз обтекаемо и неточно - можно и не париться сильно, опять же имхо

**Comment by vladon** [comment]
@artemius1248 ну т.е. не до чего было докопаться, пришлось поискать, ну понятно. Я бы докопался, что не вынес это всё в отдельную функцию, но не более.

PS А функция `_getch()` скоро будет недоступна вообще.

**Comment by artemius1248** [comment]
Не преследую никаких целей насчет вас, нет никакого интереса. тем более не вижу необходимости докапываться. Я выразил свое экспертное личное мнение, которое может не совпадать с мнением других разработчиков. Но вы право слишком принимаете близко к сердцу. Не беспокойтесь.
